# Generated by Django 5.2.1 on 2025-07-05 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivo',
            name='marca_computadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interactivo',
            name='modelo_computadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('fecha_instalado', models.DateField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sala')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statusinteractivo')),
            ],
        ),
    ]
