# Generated by Django 5.2.1 on 2025-07-10 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interactivo_marca_computadora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.PositiveSmallIntegerField(help_text='1 = Urgente, 2 = Alta, 3 = Media, 4 = Baja', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportefalla',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='reportes_fallas/'),
        ),
        migrations.CreateModel(
            name='Calendarizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
                ('interactivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.interactivo')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tareamantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.nivelprioridad'),
        ),
        migrations.AddField(
            model_name='estadotarea',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.statusmantenimiento'),
        ),
        migrations.AlterField(
            model_name='reportefalla',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.statusmantenimiento'),
        ),
        migrations.AlterField(
            model_name='reportemantenimiento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.statusmantenimiento'),
        ),
    ]
