# Generated by Django 5.2.1 on 2025-07-10 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nivelprioridad_statusmantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.statusmantenimiento'),
        ),
    ]
